#ifndef CHRONOS_COMMON_H
#define CHRONOS_COMMON_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

#define CHRONOS_MAX_FRAME_SIZE 16384
#define CHRONOS_MAX_HEADER_SIZE 8192
#define CHRONOS_MAX_STREAMS 1000
#define CHRONOS_DEFAULT_WINDOW_SIZE 65535
#define CHRONOS_MAX_CONNECTIONS 10000
#define CHRONOS_MAX_PRIORITY_LEVELS 256
#define CHRONOS_MAX_FRAGMENTS 64
#define CHRONOS_POOL_BLOCK_SIZE 4096
#define CHRONOS_POOL_MAX_BLOCKS 1024
#define CHRONOS_SESSION_CACHE_SIZE 128

typedef enum {
    CHRONOS_OK = 0,
    CHRONOS_ERROR_INVALID_INPUT = -1,
    CHRONOS_ERROR_BUFFER_TOO_SMALL = -2,
    CHRONOS_ERROR_INVALID_STATE = -3,
    CHRONOS_ERROR_OUT_OF_MEMORY = -4,
    CHRONOS_ERROR_TIMEOUT = -5,
    CHRONOS_ERROR_PROTOCOL_VIOLATION = -6,
    CHRONOS_ERROR_STREAM_CLOSED = -7,
    CHRONOS_ERROR_FLOW_CONTROL = -8,
} chronos_error_t;

typedef enum {
    CONN_STATE_IDLE = 0,
    CONN_STATE_CONNECTING = 1,
    CONN_STATE_HANDSHAKE = 2,
    CONN_STATE_PREFACE = 3,
    CONN_STATE_SETTINGS = 4,
    CONN_STATE_OPEN = 5,
    CONN_STATE_CLOSING = 6,
    CONN_STATE_CLOSED = 7,
    CONN_STATE_DRAINING = 8,
    CONN_STATE_ERROR = 9,
} connection_state_t;

typedef enum {
    SESSION_STATE_INITIAL = 0,
    SESSION_STATE_NEGOTIATING = 1,
    SESSION_STATE_ESTABLISHED = 2,
    SESSION_STATE_RESUMING = 3,
    SESSION_STATE_RENEGOTIATING = 4,
    SESSION_STATE_EXPIRED = 5,
    SESSION_STATE_INVALID = 6,
} session_state_t;

typedef enum {
    POOL_STATE_CLEAN = 0,
    POOL_STATE_FRAGMENTED = 1,
    POOL_STATE_CORRUPTED = 2,
    POOL_STATE_RECOVERING = 3,
} pool_state_t;

